-- 5.1 — FLV6 Schema Streams (2) --

sql
CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_FLIGHT_LOGS
  ON TABLE DRONE_DELIVERY_DB.FLV6.FLIGHT_LOGS
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on flight telemetry logs';

CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_WEATHER_DATA
  ON TABLE DRONE_DELIVERY_DB.FLV6.WEATHER_DATA
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on weather data';




-- 5.2 — DELIVERY Schema Streams (3) --

sql
CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_ORDERS
  ON TABLE DRONE_DELIVERY_DB.DELIVERY.ORDERS
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on customer orders';

CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_CUSTOMERS
  ON TABLE DRONE_DELIVERY_DB.DELIVERY.CUSTOMERS
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on customers';

CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_DELIVERY_FEEDBACK
  ON TABLE DRONE_DELIVERY_DB.DELIVERY.DELIVERY_FEEDBACK
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on delivery feedback';



-- 5.3 — API Schema Streams (2) --

sql
CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_MISSIONS
  ON TABLE DRONE_DELIVERY_DB.API.MISSIONS
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on missions';

CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_MISSION_EVENTS
  ON TABLE DRONE_DELIVERY_DB.API.MISSION_EVENTS
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream capturing INSERT/UPDATE/DELETE on mission events';



-- 5.4 — GEO Schema Streams (2) --

sql
CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_DELIVERY_ZONES
  ON TABLE DRONE_DELIVERY_DB.GEO.DELIVERY_ZONES
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on delivery zones';

CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_NO_FLY_ZONES
  ON TABLE DRONE_DELIVERY_DB.GEO.NO_FLY_ZONES
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on no-fly zones';



-- 5.5 — OSRM Schema Streams (2) --

sql
CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_ROUTES
  ON TABLE DRONE_DELIVERY_DB.OSRM.ROUTES
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on routes';

CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_ROUTE_SEGMENTS
  ON TABLE DRONE_DELIVERY_DB.OSRM.ROUTE_SEGMENTS
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on route segments';




-- 5.6 — DEPOT Schema Streams (3) --

sql
CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_AIRCRAFT
  ON TABLE DRONE_DELIVERY_DB.DEPOT.AIRCRAFT
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on aircraft fleet';

CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_PARTS_INVENTORY
  ON TABLE DRONE_DELIVERY_DB.DEPOT.PARTS_INVENTORY
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on parts inventory';

CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_DEPOTS
  ON TABLE DRONE_DELIVERY_DB.DEPOT.DEPOTS
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on depot locations';




-- 5.7 — RECORDS Schema Streams (2) --
 
 sql
CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_MAINTENANCE_LOGS
  ON TABLE DRONE_DELIVERY_DB.RECORDS.MAINTENANCE_LOGS
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on maintenance logs';

CREATE OR REPLACE STREAM DRONE_DELIVERY_DB.BRONZE.STREAM_PARTS_USED
  ON TABLE DRONE_DELIVERY_DB.RECORDS.PARTS_USED
  APPEND_ONLY = FALSE SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'CDC stream on parts used';

Validation Command
sql
SHOW STREAMS IN SCHEMA DRONE_DELIVERY_DB.BRONZE;


-- How Streams Feed the dbt Bronze Layer
-- text
-- Raw Table → Snowflake Stream → dbt Incremental Model (Bronze)
--                                   ├── METADATA$ACTION → _CDC_ACTION
--                                   ├── METADATA$ISUPDATE → _CDC_IS_UPDATE
--                                   └── CURRENT_TIMESTAMP() → _DBT_LOADED_AT
