-- 1.1 — Role Creation --

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS DRONE_ADMIN
  COMMENT = 'Full ownership of drone delivery database, schemas, and objects';

CREATE ROLE IF NOT EXISTS DRONE_ENGINEER
  COMMENT = 'Read/write on all schemas, run dbt, create objects';

CREATE ROLE IF NOT EXISTS DRONE_ANALYST
  COMMENT = 'Read-only on silver/gold/analytics layers, run Streamlit dashboard';

CREATE ROLE IF NOT EXISTS DRONE_LOADER
  COMMENT = 'Write-only on raw schemas for data ingestion';



--- Role Hierarchy --

-----SYSADMIN
--   └── DRONE_ADMIN
--         ├── DRONE_ENGINEER
--         │     └── DRONE_LOADER
--         └── DRONE_ANALYST

GRANT ROLE DRONE_ADMIN    TO ROLE SYSADMIN;
GRANT ROLE DRONE_ENGINEER TO ROLE DRONE_ADMIN;
GRANT ROLE DRONE_ANALYST  TO ROLE DRONE_ADMIN;
GRANT ROLE DRONE_LOADER   TO ROLE DRONE_ENGINEER;



-- 1.3 — Warehouse Creation --
CREATE WAREHOUSE IF NOT EXISTS DRONE_INGEST_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Synthetic data generation and raw data loading';

CREATE WAREHOUSE IF NOT EXISTS DRONE_TRANSFORM_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'dbt transformations and AI functions';

CREATE WAREHOUSE IF NOT EXISTS DRONE_ANALYTICS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60

AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Streamlit dashboard queries';



-- 1.4 — Warehouse Grants --
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE DRONE_INGEST_WH    TO ROLE DRONE_ADMIN;
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE DRONE_TRANSFORM_WH TO ROLE DRONE_ADMIN;
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE DRONE_ANALYTICS_WH TO ROLE DRONE_ADMIN;

GRANT USAGE, OPERATE ON WAREHOUSE DRONE_TRANSFORM_WH TO ROLE DRONE_ENGINEER;
GRANT USAGE         ON WAREHOUSE DRONE_ANALYTICS_WH  TO ROLE DRONE_ANALYST;
GRANT USAGE, OPERATE ON WAREHOUSE DRONE_INGEST_WH    TO ROLE DRONE_LOADER;


-- 1.5 — Cortex AI Grants --
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE DRONE_ENGINEER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE DRONE_ANALYST;

GRANT USE AI FUNCTIONS ON ACCOUNT TO ROLE DRONE_ENGINEER;
GRANT USE AI FUNCTIONS ON ACCOUNT TO ROLE DRONE_ANALYST;

GRANT ROLE DRONE_ADMIN TO USER INDU;
GRANT ROLE DRONE_ADMIN TO USER SANDEEP;
