-- 1.1 — Database Creation --

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS DRONE_DELIVERY_DB
  COMMENT = 'Drone delivery data platform - medallion architecture';



-- 1.2 — Raw Source Schemas --

CREATE SCHEMA IF NOT EXISTS DRONE_DELIVERY_DB.FLV6
  COMMENT = 'Flight logs and weather telemetry';

CREATE SCHEMA IF NOT EXISTS DRONE_DELIVERY_DB.DELIVERY
  COMMENT = 'Customer orders, customers, delivery feedback';

CREATE SCHEMA IF NOT EXISTS DRONE_DELIVERY_DB.API
  COMMENT = 'Mission assignments and events';

CREATE SCHEMA IF NOT EXISTS DRONE_DELIVERY_DB.GEO
  COMMENT = 'Delivery zones and no-fly zones';

CREATE SCHEMA IF NOT EXISTS DRONE_DELIVERY_DB.OSRM
  COMMENT = 'Route plans and segments';

CREATE SCHEMA IF NOT EXISTS DRONE_DELIVERY_DB.DEPOT
  COMMENT = 'Aircraft fleet, parts inventory, depot locations';

CREATE SCHEMA IF NOT EXISTS DRONE_DELIVERY_DB.RECORDS
  COMMENT = 'Maintenance logs and parts consumption';



-- 1.3 — Medallion + Analytics Schemas --

CREATE SCHEMA IF NOT EXISTS DRONE_DELIVERY_DB.BRONZE
  COMMENT = 'Raw copies with CDC metadata';

CREATE SCHEMA IF NOT EXISTS DRONE_DELIVERY_DB.SILVER
  COMMENT = 'Cleaned, deduped, AI-enriched';

CREATE SCHEMA IF NOT EXISTS DRONE_DELIVERY_DB.GOLD
  COMMENT = 'Business aggregates and KPIs';

CREATE SCHEMA IF NOT EXISTS DRONE_DELIVERY_DB.ANALYTICS
  COMMENT = 'Streamlit-facing views';



-- 1.4 — Ownership Transfer --

GRANT OWNERSHIP ON DATABASE DRONE_DELIVERY_DB
  TO ROLE DRONE_ADMIN COPY CURRENT GRANTS;

GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE DRONE_DELIVERY_DB
  TO ROLE DRONE_ADMIN COPY CURRENT GRANTS;


-- 1.5 — Direct Grants (Database & Schema Level) --

GRANT USAGE ON DATABASE DRONE_DELIVERY_DB TO ROLE DRONE_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DRONE_DELIVERY_DB TO ROLE DRONE_ENGINEER;

-- CREATE on medallion schemas
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA DRONE_DELIVERY_DB.BRONZE    TO ROLE DRONE_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA DRONE_DELIVERY_DB.SILVER    TO ROLE DRONE_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA DRONE_DELIVERY_DB.GOLD      TO ROLE DRONE_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA DRONE_DELIVERY_DB.ANALYTICS TO ROLE DRONE_ENGINEER;

-- SELECT on raw schemas (0 objects affected — tables don't exist yet, covered by future grants)
GRANT SELECT ON ALL TABLES IN SCHEMA DRONE_DELIVERY_DB.FLV6     TO ROLE DRONE_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA DRONE_DELIVERY_DB.DELIVERY TO ROLE DRONE_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA DRONE_DELIVERY_DB.API      TO ROLE DRONE_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA DRONE_DELIVERY_DB.GEO      TO ROLE DRONE_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA DRONE_DELIVERY_DB.OSRM     TO ROLE DRONE_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA DRONE_DELIVERY_DB.DEPOT    TO ROLE DRONE_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA DRONE_DELIVERY_DB.RECORDS  TO ROLE DRONE_ENGINEER;

-- DRONE_ANALYST — SILVER, GOLD, ANALYTICS Only
GRANT USAGE ON DATABASE DRONE_DELIVERY_DB TO ROLE DRONE_LOADER;

GRANT USAGE ON SCHEMA DRONE_DELIVERY_DB.FLV6     TO ROLE DRONE_LOADER;
GRANT USAGE ON SCHEMA DRONE_DELIVERY_DB.DELIVERY TO ROLE DRONE_LOADER;
GRANT USAGE ON SCHEMA DRONE_DELIVERY_DB.API      TO ROLE DRONE_LOADER;
GRANT USAGE ON SCHEMA DRONE_DELIVERY_DB.GEO      TO ROLE DRONE_LOADER;
GRANT USAGE ON SCHEMA DRONE_DELIVERY_DB.OSRM     TO ROLE DRONE_LOADER;
GRANT USAGE ON SCHEMA DRONE_DELIVERY_DB.DEPOT    TO ROLE DRONE_LOADER;
GRANT USAGE ON SCHEMA DRONE_DELIVERY_DB.RECORDS  TO ROLE DRONE_LOADER;



-- 2.6 — Future Grants (Auto-Inherit on New Objects) --

-- DRONE_ENGINEER — SELECT on future raw tables
GRANT SELECT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.FLV6     TO ROLE DRONE_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.DELIVERY TO ROLE DRONE_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.API      TO ROLE DRONE_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.GEO      TO ROLE DRONE_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.OSRM     TO ROLE DRONE_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.DEPOT    TO ROLE DRONE_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.RECORDS  TO ROLE DRONE_ENGINEER;


-- DRONE_ENGINEER — Full CRUD on future medallion tables + views
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.BRONZE    TO ROLE DRONE_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.SILVER    TO ROLE DRONE_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.GOLD      TO ROLE DRONE_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.ANALYTICS TO ROLE DRONE_ENGINEER;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA DRONE_DELIVERY_DB.BRONZE TO ROLE DRONE_ENGINEER;


--DRONE_ANALYST — SELECT on future SILVER/GOLD/ANALYTICS tables + views
GRANT SELECT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.SILVER    TO ROLE DRONE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.GOLD      TO ROLE DRONE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.ANALYTICS TO ROLE DRONE_ANALYST;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA DRONE_DELIVERY_DB.SILVER    TO ROLE DRONE_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DRONE_DELIVERY_DB.GOLD      TO ROLE DRONE_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DRONE_DELIVERY_DB.ANALYTICS TO ROLE DRONE_ANALYST;


-- DRONE_LOADER — INSERT on future raw tables
GRANT INSERT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.FLV6     TO ROLE DRONE_LOADER;
GRANT INSERT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.DELIVERY TO ROLE DRONE_LOADER;
GRANT INSERT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.API      TO ROLE DRONE_LOADER;
GRANT INSERT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.GEO      TO ROLE DRONE_LOADER;
GRANT INSERT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.OSRM     TO ROLE DRONE_LOADER;
GRANT INSERT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.DEPOT    TO ROLE DRONE_LOADER;
GRANT INSERT ON FUTURE TABLES IN SCHEMA DRONE_DELIVERY_DB.RECORDS  TO ROLE DRONE_LOADER
