-- 1.0 — Context Setup -- 

USE ROLE DRONE_ADMIN;
USE DATABASE DRONE_DELIVERY_DB;
USE WAREHOUSE DRONE_INGEST_WH;



-- 1.1 — FLV6 Schema (2 tables) --

CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.FLV6.FLIGHT_LOGS (
    FLIGHT_LOG_ID   VARCHAR(36)     NOT NULL,
    AIRCRAFT_ID     VARCHAR(36)     NOT NULL,
    RECORDED_AT     TIMESTAMP_NTZ   NOT NULL,
    LAT             FLOAT           NOT NULL,
    LON             FLOAT           NOT NULL,
    ALTITUDE_M      FLOAT,
    SPEED_KMH       FLOAT,
    BATTERY_PCT     FLOAT,
    HEADING_DEG     FLOAT,
    _LOADED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE    VARCHAR         DEFAULT 'SYNTHETIC'
);

CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.FLV6.WEATHER_DATA (
    WEATHER_ID          VARCHAR(36)     NOT NULL,
    STATION_ID          VARCHAR(36)     NOT NULL,
    RECORDED_AT         TIMESTAMP_NTZ   NOT NULL,
    TEMP_C              FLOAT,
    WIND_SPEED_KMH      FLOAT,
    WIND_DIRECTION_DEG  FLOAT,
    VISIBILITY_KM       FLOAT,
    PRECIPITATION_MM    FLOAT,
    CONDITIONS          VARCHAR(50),
    _LOADED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE        VARCHAR         DEFAULT 'SYNTHETIC'
);



-- 1.2 — DELIVERY Schema (3 tables) --

CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.DELIVERY.ORDERS (
    ORDER_ID            VARCHAR(36)     NOT NULL,
    CUSTOMER_ID         VARCHAR(36)     NOT NULL,
    PICKUP_LAT          FLOAT           NOT NULL,
    PICKUP_LON          FLOAT           NOT NULL,
    DROPOFF_LAT         FLOAT           NOT NULL,
    DROPOFF_LON         FLOAT           NOT NULL,
    PACKAGE_WEIGHT_KG   FLOAT,
    PRIORITY            VARCHAR(20)     DEFAULT 'STANDARD',
    STATUS              VARCHAR(20)     NOT NULL,
    CREATED_AT          TIMESTAMP_NTZ   NOT NULL,
    DELIVERED_AT        TIMESTAMP_NTZ,
    _LOADED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE        VARCHAR         DEFAULT 'SYNTHETIC'
);

CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.DELIVERY.CUSTOMERS (
    CUSTOMER_ID     VARCHAR(36)     NOT NULL,
    NAME            VARCHAR(200)    NOT NULL,
    EMAIL           VARCHAR(200),
    PHONE           VARCHAR(30),
    ADDRESS         VARCHAR(500),
    CREATED_AT      TIMESTAMP_NTZ   NOT NULL,
    _LOADED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE    VARCHAR         DEFAULT 'SYNTHETIC'
);

CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.DELIVERY.DELIVERY_FEEDBACK (
    FEEDBACK_ID         VARCHAR(36)     NOT NULL,
    ORDER_ID            VARCHAR(36)     NOT NULL,
    CUSTOMER_ID         VARCHAR(36)     NOT NULL,
    RATING              INT             NOT NULL,
    COMMENTS            TEXT,
    FEEDBACK_CHANNEL    VARCHAR(20),
    CREATED_AT          TIMESTAMP_NTZ   NOT NULL,
    _LOADED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE        VARCHAR         DEFAULT 'SYNTHETIC'
);



-- 1.3 — API Schema (2 tables) --

CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.API.MISSIONS (
    MISSION_ID          VARCHAR(36)     NOT NULL,
    ORDER_ID            VARCHAR(36)     NOT NULL,
    AIRCRAFT_ID         VARCHAR(36)     NOT NULL,
    STATUS              VARCHAR(20)     NOT NULL,
    PLANNED_DEPARTURE   TIMESTAMP_NTZ,
    ACTUAL_DEPARTURE    TIMESTAMP_NTZ,
    PLANNED_ARRIVAL     TIMESTAMP_NTZ,
    ACTUAL_ARRIVAL      TIMESTAMP_NTZ,
    NOTES               TEXT,
    _LOADED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE        VARCHAR         DEFAULT 'SYNTHETIC'
);

CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.API.MISSION_EVENTS (
    EVENT_ID            VARCHAR(36)     NOT NULL,
    MISSION_ID          VARCHAR(36)     NOT NULL,
    EVENT_TYPE          VARCHAR(50)     NOT NULL,
    EVENT_TIMESTAMP     TIMESTAMP_NTZ   NOT NULL,
    DESCRIPTION         TEXT,
    LAT                 FLOAT,
    LON                 FLOAT,
    _LOADED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE        VARCHAR         DEFAULT 'SYNTHETIC'
);



-- 1.4 — GEO Schema (2 tables) --
sql
CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.GEO.DELIVERY_ZONES (
    ZONE_ID         VARCHAR(36)     NOT NULL,
    ZONE_NAME       VARCHAR(100)    NOT NULL,
    CENTER_LAT      FLOAT           NOT NULL,
    CENTER_LON      FLOAT           NOT NULL,
    RADIUS_KM       FLOAT           NOT NULL,
    ZONE_TYPE       VARCHAR(30),
    IS_ACTIVE       BOOLEAN         DEFAULT TRUE,
    _LOADED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE    VARCHAR         DEFAULT 'SYNTHETIC'
);

CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.GEO.NO_FLY_ZONES (
    NFZ_ID              VARCHAR(36)     NOT NULL,
    ZONE_NAME           VARCHAR(100)    NOT NULL,
    CENTER_LAT          FLOAT           NOT NULL,
    CENTER_LON          FLOAT           NOT NULL,
    RADIUS_KM           FLOAT           NOT NULL,
    RESTRICTION_TYPE    VARCHAR(30)     NOT NULL,
    EFFECTIVE_FROM      TIMESTAMP_NTZ   NOT NULL,
    EFFECTIVE_TO        TIMESTAMP_NTZ,
    _LOADED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE        VARCHAR         DEFAULT 'SYNTHETIC'
);

-- 1.5 — OSRM Schema (2 tables) --
sql
CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.OSRM.ROUTES (
    ROUTE_ID        VARCHAR(36)     NOT NULL,
    MISSION_ID      VARCHAR(36)     NOT NULL,
    ORIGIN_LAT      FLOAT           NOT NULL,
    ORIGIN_LON      FLOAT           NOT NULL,
    DEST_LAT        FLOAT           NOT NULL,
    DEST_LON        FLOAT           NOT NULL,
    DISTANCE_KM     FLOAT,
    DURATION_MIN    FLOAT,
    WAYPOINTS       VARIANT,
    _LOADED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE    VARCHAR         DEFAULT 'SYNTHETIC'
);

CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.OSRM.ROUTE_SEGMENTS (
    SEGMENT_ID      VARCHAR(36)     NOT NULL,
    ROUTE_ID        VARCHAR(36)     NOT NULL,
    SEGMENT_SEQ     INT             NOT NULL,
    START_LAT       FLOAT           NOT NULL,
    START_LON       FLOAT           NOT NULL,
    END_LAT         FLOAT           NOT NULL,
    END_LON         FLOAT           NOT NULL,
    DISTANCE_KM     FLOAT,
    ALTITUDE_M      FLOAT,
    _LOADED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE    VARCHAR         DEFAULT 'SYNTHETIC'
);

-- 1.6 — DEPOT Schema (3 tables) -- 
sql
CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.DEPOT.AIRCRAFT (
    AIRCRAFT_ID             VARCHAR(36)     NOT NULL,
    MODEL                   VARCHAR(100)    NOT NULL,
    SERIAL_NUMBER           VARCHAR(50)     NOT NULL,
    STATUS                  VARCHAR(20)     NOT NULL,
    DEPOT_ID                VARCHAR(36)     NOT NULL,
    TOTAL_FLIGHT_HOURS      FLOAT           DEFAULT 0,
    LAST_MAINTENANCE_DATE   DATE,
    _LOADED_AT              TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE            VARCHAR         DEFAULT 'SYNTHETIC'
);

CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.DEPOT.PARTS_INVENTORY (
    PART_ID             VARCHAR(36)     NOT NULL,
    PART_NAME           VARCHAR(200)    NOT NULL,
    CATEGORY            VARCHAR(50),
    QUANTITY_ON_HAND    INT             DEFAULT 0,
    REORDER_LEVEL       INT             DEFAULT 0,
    UNIT_COST           FLOAT,
    DEPOT_ID            VARCHAR(36)     NOT NULL,
    _LOADED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE        VARCHAR         DEFAULT 'SYNTHETIC'
);

CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.DEPOT.DEPOTS (
    DEPOT_ID        VARCHAR(36)     NOT NULL,
    DEPOT_NAME      VARCHAR(100)    NOT NULL,
    LAT             FLOAT           NOT NULL,
    LON             FLOAT           NOT NULL,
    CAPACITY        INT,
    _LOADED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE    VARCHAR         DEFAULT 'SYNTHETIC'
);

-- 1.7 — RECORDS Schema (2 tables) --
sql
CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.RECORDS.MAINTENANCE_LOGS (
    LOG_ID              VARCHAR(36)     NOT NULL,
    AIRCRAFT_ID         VARCHAR(36)     NOT NULL,
    MAINTENANCE_TYPE    VARCHAR(30)     NOT NULL,
    DESCRIPTION         TEXT,
    TECHNICIAN          VARCHAR(100),
    STARTED_AT          TIMESTAMP_NTZ   NOT NULL,
    COMPLETED_AT        TIMESTAMP_NTZ,
    STATUS              VARCHAR(20)     NOT NULL,
    _LOADED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE        VARCHAR         DEFAULT 'SYNTHETIC'
);

CREATE TABLE IF NOT EXISTS DRONE_DELIVERY_DB.RECORDS.PARTS_USED (
    USAGE_ID        VARCHAR(36)     NOT NULL,
    LOG_ID          VARCHAR(36)     NOT NULL,
    PART_ID         VARCHAR(36)     NOT NULL,
    QUANTITY_USED   INT             NOT NULL,
    COST            FLOAT,
    _LOADED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE    VARCHAR         DEFAULT 'SYNTHETIC'
);


-- DELIVERY.ORDERS.CUSTOMER_ID         → DELIVERY.CUSTOMERS.CUSTOMER_ID
-- DELIVERY.DELIVERY_FEEDBACK.ORDER_ID → DELIVERY.ORDERS.ORDER_ID
-- DELIVERY.DELIVERY_FEEDBACK.CUSTOMER_ID → DELIVERY.CUSTOMERS.CUSTOMER_ID
-- API.MISSIONS.ORDER_ID               → DELIVERY.ORDERS.ORDER_ID
-- API.MISSIONS.AIRCRAFT_ID            → DEPOT.AIRCRAFT.AIRCRAFT_ID
-- API.MISSION_EVENTS.MISSION_ID       → API.MISSIONS.MISSION_ID
-- OSRM.ROUTES.MISSION_ID              → API.MISSIONS.MISSION_ID
-- OSRM.ROUTE_SEGMENTS.ROUTE_ID        → OSRM.ROUTES.ROUTE_ID
-- DEPOT.AIRCRAFT.DEPOT_ID             → DEPOT.DEPOTS.DEPOT_ID
-- DEPOT.PARTS_INVENTORY.DEPOT_ID      → DEPOT.DEPOTS.DEPOT_ID
-- RECORDS.MAINTENANCE_LOGS.AIRCRAFT_ID → DEPOT.AIRCRAFT.AIRCRAFT_ID
-- RECORDS.PARTS_USED.LOG_ID           → RECORDS.MAINTENANCE_LOGS.LOG_ID
-- RECORDS.PARTS_USED.PART_ID          → DEPOT.PARTS_INVENTORY.PART_ID
-- FLV6.FLIGHT_LOGS.AIRCRAFT_ID        → DEPOT.AIRCRAFT.AIRCRAFT_ID
