-- ============================================================================
-- PHASE 8: VALIDATION SCRIPTS
-- Drone Delivery Platform - Data Quality & Integrity Checks
-- Run these after each dbt build to ensure data correctness
-- ============================================================================


-- ============================================================================
-- SECTION 1: ROW COUNT VALIDATION (Bronze vs Source)
-- Ensures Bronze layer captured all source records
-- ============================================================================

SELECT 'AIRCRAFT' AS entity,
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DEPOT.AIRCRAFT) AS source_count,
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_AIRCRAFT) AS bronze_count,
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DEPOT.AIRCRAFT) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_AIRCRAFT)
            THEN 'PASS' ELSE 'FAIL' END AS status
UNION ALL
SELECT 'CUSTOMERS',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DELIVERY.CUSTOMERS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_CUSTOMERS),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DELIVERY.CUSTOMERS) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_CUSTOMERS)
            THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'DELIVERY_FEEDBACK',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DELIVERY.DELIVERY_FEEDBACK),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_DELIVERY_FEEDBACK),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DELIVERY.DELIVERY_FEEDBACK) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_DELIVERY_FEEDBACK)
            THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'ORDERS',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DELIVERY.ORDERS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_ORDERS),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DELIVERY.ORDERS) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_ORDERS)
            THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'FLIGHT_LOGS',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.FLV6.FLIGHT_LOGS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_FLIGHT_LOGS),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.FLV6.FLIGHT_LOGS) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_FLIGHT_LOGS)
            THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'MISSIONS',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.API.MISSIONS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_MISSIONS),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.API.MISSIONS) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_MISSIONS)
            THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'MISSION_EVENTS',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.API.MISSION_EVENTS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_MISSION_EVENTS),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.API.MISSION_EVENTS) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_MISSION_EVENTS)
            THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'MAINTENANCE_LOGS',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.RECORDS.MAINTENANCE_LOGS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_MAINTENANCE_LOGS),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.RECORDS.MAINTENANCE_LOGS) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_MAINTENANCE_LOGS)
            THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'PARTS_USED',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.RECORDS.PARTS_USED),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_PARTS_USED),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.RECORDS.PARTS_USED) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_PARTS_USED)
            THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'PARTS_INVENTORY',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DEPOT.PARTS_INVENTORY),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_PARTS_INVENTORY),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DEPOT.PARTS_INVENTORY) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_PARTS_INVENTORY)
            THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'ROUTES',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.OSRM.ROUTES),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_ROUTES),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.OSRM.ROUTES) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_ROUTES)
            THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'ROUTE_SEGMENTS',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.OSRM.ROUTE_SEGMENTS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_ROUTE_SEGMENTS),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.OSRM.ROUTE_SEGMENTS) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_ROUTE_SEGMENTS)
            THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'DELIVERY_ZONES',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GEO.DELIVERY_ZONES),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_DELIVERY_ZONES),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GEO.DELIVERY_ZONES) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_DELIVERY_ZONES)
            THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'NO_FLY_ZONES',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GEO.NO_FLY_ZONES),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_NO_FLY_ZONES),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GEO.NO_FLY_ZONES) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_NO_FLY_ZONES)
            THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'DEPOTS',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DEPOT.DEPOTS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_DEPOTS),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DEPOT.DEPOTS) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_DEPOTS)
            THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT 'WEATHER_DATA',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.FLV6.WEATHER_DATA),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_WEATHER_DATA),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.FLV6.WEATHER_DATA) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_WEATHER_DATA)
            THEN 'PASS' ELSE 'FAIL' END;


-- ============================================================================
-- SECTION 2: PRIMARY KEY UNIQUENESS (Silver Layer)
-- Ensures no duplicates after dedup/cleaning
-- ============================================================================

SELECT 'SILVER_AIRCRAFT' AS model, 'aircraft_id' AS pk_column,
       COUNT(*) AS total_rows, COUNT(DISTINCT aircraft_id) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT aircraft_id) THEN 'PASS' ELSE 'FAIL' END AS status
FROM DRONE_DELIVERY_DB.SILVER.SILVER_AIRCRAFT
UNION ALL
SELECT 'SILVER_CUSTOMERS', 'customer_id',
       COUNT(*), COUNT(DISTINCT customer_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT customer_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_CUSTOMERS
UNION ALL
SELECT 'SILVER_DELIVERY_FEEDBACK', 'feedback_id',
       COUNT(*), COUNT(DISTINCT feedback_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT feedback_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_DELIVERY_FEEDBACK
UNION ALL
SELECT 'SILVER_ORDERS', 'order_id',
       COUNT(*), COUNT(DISTINCT order_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT order_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_ORDERS
UNION ALL
SELECT 'SILVER_MISSIONS', 'mission_id',
       COUNT(*), COUNT(DISTINCT mission_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT mission_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_MISSIONS
UNION ALL
SELECT 'SILVER_FLIGHT_LOGS', 'flight_log_id',
       COUNT(*), COUNT(DISTINCT flight_log_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT flight_log_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_FLIGHT_LOGS
UNION ALL
SELECT 'SILVER_MAINTENANCE_LOGS', 'log_id',
       COUNT(*), COUNT(DISTINCT log_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT log_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_MAINTENANCE_LOGS
UNION ALL
SELECT 'SILVER_ROUTES', 'route_id',
       COUNT(*), COUNT(DISTINCT route_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT route_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_ROUTES
UNION ALL
SELECT 'SILVER_PARTS_INVENTORY', 'part_id',
       COUNT(*), COUNT(DISTINCT part_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT part_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_PARTS_INVENTORY
UNION ALL
SELECT 'SILVER_PARTS_USED', 'usage_id',
       COUNT(*), COUNT(DISTINCT usage_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT usage_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_PARTS_USED
UNION ALL
SELECT 'SILVER_DELIVERY_ZONES', 'zone_id',
       COUNT(*), COUNT(DISTINCT zone_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT zone_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_DELIVERY_ZONES
UNION ALL
SELECT 'SILVER_NO_FLY_ZONES', 'nfz_id',
       COUNT(*), COUNT(DISTINCT nfz_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT nfz_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_NO_FLY_ZONES
UNION ALL
SELECT 'SILVER_DEPOTS', 'depot_id',
       COUNT(*), COUNT(DISTINCT depot_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT depot_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_DEPOTS
UNION ALL
SELECT 'SILVER_WEATHER_DATA', 'weather_id',
       COUNT(*), COUNT(DISTINCT weather_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT weather_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_WEATHER_DATA
UNION ALL
SELECT 'SILVER_MISSION_EVENTS', 'event_id',
       COUNT(*), COUNT(DISTINCT event_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT event_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_MISSION_EVENTS
UNION ALL
SELECT 'SILVER_ROUTE_SEGMENTS', 'segment_id',
       COUNT(*), COUNT(DISTINCT segment_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT segment_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_ROUTE_SEGMENTS;


-- ============================================================================
-- SECTION 3: NULL CHECK ON CRITICAL COLUMNS (Silver Layer)
-- Ensures NOT NULL constraints on key business columns
-- ============================================================================

SELECT 'SILVER_AIRCRAFT.aircraft_id' AS check_column,
       SUM(CASE WHEN aircraft_id IS NULL THEN 1 ELSE 0 END) AS null_count,
       CASE WHEN SUM(CASE WHEN aircraft_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END AS status
FROM DRONE_DELIVERY_DB.SILVER.SILVER_AIRCRAFT
UNION ALL
SELECT 'SILVER_CUSTOMERS.customer_id',
       SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_CUSTOMERS
UNION ALL
SELECT 'SILVER_ORDERS.order_id',
       SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_ORDERS
UNION ALL
SELECT 'SILVER_ORDERS.customer_id',
       SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_ORDERS
UNION ALL
SELECT 'SILVER_MISSIONS.mission_id',
       SUM(CASE WHEN mission_id IS NULL THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN mission_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_MISSIONS
UNION ALL
SELECT 'SILVER_MISSIONS.aircraft_id',
       SUM(CASE WHEN aircraft_id IS NULL THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN aircraft_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_MISSIONS
UNION ALL
SELECT 'SILVER_FLIGHT_LOGS.aircraft_id',
       SUM(CASE WHEN aircraft_id IS NULL THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN aircraft_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_FLIGHT_LOGS
UNION ALL
SELECT 'SILVER_DELIVERY_FEEDBACK.order_id',
       SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_DELIVERY_FEEDBACK
UNION ALL
SELECT 'SILVER_MAINTENANCE_LOGS.aircraft_id',
       SUM(CASE WHEN aircraft_id IS NULL THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN aircraft_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_MAINTENANCE_LOGS
UNION ALL
SELECT 'SILVER_ROUTES.mission_id',
       SUM(CASE WHEN mission_id IS NULL THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN mission_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_ROUTES;


-- ============================================================================
-- SECTION 4: REFERENTIAL INTEGRITY CHECKS (Silver Layer)
-- Ensures foreign key relationships are valid
-- ============================================================================

SELECT 'ORDERS → CUSTOMERS' AS relationship,
       COUNT(*) AS orphan_count,
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END AS status
FROM DRONE_DELIVERY_DB.SILVER.SILVER_ORDERS o
WHERE NOT EXISTS (
    SELECT 1 FROM DRONE_DELIVERY_DB.SILVER.SILVER_CUSTOMERS c
    WHERE c.customer_id = o.customer_id
)
UNION ALL
SELECT 'MISSIONS → ORDERS',
       COUNT(*),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_MISSIONS m
WHERE NOT EXISTS (
    SELECT 1 FROM DRONE_DELIVERY_DB.SILVER.SILVER_ORDERS o
    WHERE o.order_id = m.order_id
)
UNION ALL
SELECT 'MISSIONS → AIRCRAFT',
       COUNT(*),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_MISSIONS m
WHERE NOT EXISTS (
    SELECT 1 FROM DRONE_DELIVERY_DB.SILVER.SILVER_AIRCRAFT a
    WHERE a.aircraft_id = m.aircraft_id
)
UNION ALL
SELECT 'MISSION_EVENTS → MISSIONS',
       COUNT(*),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_MISSION_EVENTS me
WHERE NOT EXISTS (
    SELECT 1 FROM DRONE_DELIVERY_DB.SILVER.SILVER_MISSIONS m
    WHERE m.mission_id = me.mission_id
)
UNION ALL
SELECT 'ROUTES → MISSIONS',
       COUNT(*),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_ROUTES r
WHERE NOT EXISTS (
    SELECT 1 FROM DRONE_DELIVERY_DB.SILVER.SILVER_MISSIONS m
    WHERE m.mission_id = r.mission_id
)
UNION ALL
SELECT 'FEEDBACK → ORDERS',
       COUNT(*),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_DELIVERY_FEEDBACK f
WHERE NOT EXISTS (
    SELECT 1 FROM DRONE_DELIVERY_DB.SILVER.SILVER_ORDERS o
    WHERE o.order_id = f.order_id
)
UNION ALL
SELECT 'AIRCRAFT → DEPOTS',
       COUNT(*),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_AIRCRAFT a
WHERE NOT EXISTS (
    SELECT 1 FROM DRONE_DELIVERY_DB.SILVER.SILVER_DEPOTS d
    WHERE d.depot_id = a.depot_id
)
UNION ALL
SELECT 'PARTS_INVENTORY → DEPOTS',
       COUNT(*),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_PARTS_INVENTORY pi
WHERE NOT EXISTS (
    SELECT 1 FROM DRONE_DELIVERY_DB.SILVER.SILVER_DEPOTS d
    WHERE d.depot_id = pi.depot_id
)
UNION ALL
SELECT 'PARTS_USED → MAINTENANCE_LOGS',
       COUNT(*),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_PARTS_USED pu
WHERE NOT EXISTS (
    SELECT 1 FROM DRONE_DELIVERY_DB.SILVER.SILVER_MAINTENANCE_LOGS ml
    WHERE ml.log_id = pu.log_id
)
UNION ALL
SELECT 'ROUTE_SEGMENTS → ROUTES',
       COUNT(*),
       CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_ROUTE_SEGMENTS rs
WHERE NOT EXISTS (
    SELECT 1 FROM DRONE_DELIVERY_DB.SILVER.SILVER_ROUTES r
    WHERE r.route_id = rs.route_id
);


-- ============================================================================
-- SECTION 5: DATA RANGE & BUSINESS RULE VALIDATION (Silver Layer)
-- Ensures derived columns and business logic are correct
-- ============================================================================

SELECT 'RATING range (1-5)' AS check_name,
       SUM(CASE WHEN rating < 1 OR rating > 5 THEN 1 ELSE 0 END) AS violation_count,
       CASE WHEN SUM(CASE WHEN rating < 1 OR rating > 5 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END AS status
FROM DRONE_DELIVERY_DB.SILVER.SILVER_DELIVERY_FEEDBACK
UNION ALL
SELECT 'SENTIMENT_SCORE range (-1 to 1)',
       SUM(CASE WHEN sentiment_score < -1 OR sentiment_score > 1 THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN sentiment_score < -1 OR sentiment_score > 1 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_DELIVERY_FEEDBACK
UNION ALL
SELECT 'BATTERY_PCT range (0-100)',
       SUM(CASE WHEN battery_pct < 0 OR battery_pct > 100 THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN battery_pct < 0 OR battery_pct > 100 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_FLIGHT_LOGS
UNION ALL
SELECT 'SPEED_KMH non-negative',
       SUM(CASE WHEN speed_kmh < 0 THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN speed_kmh < 0 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_FLIGHT_LOGS
UNION ALL
SELECT 'ALTITUDE_M non-negative',
       SUM(CASE WHEN altitude_m < 0 THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN altitude_m < 0 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_FLIGHT_LOGS
UNION ALL
SELECT 'PACKAGE_WEIGHT_KG positive',
       SUM(CASE WHEN package_weight_kg <= 0 THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN package_weight_kg <= 0 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_ORDERS
UNION ALL
SELECT 'DISTANCE_KM non-negative',
       SUM(CASE WHEN distance_km < 0 THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN distance_km < 0 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_ROUTES
UNION ALL
SELECT 'PRIORITY accepted values',
       SUM(CASE WHEN priority NOT IN ('STANDARD', 'EXPRESS', 'URGENT', 'PREMIUM') THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN priority NOT IN ('STANDARD', 'EXPRESS', 'URGENT', 'PREMIUM') THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_ORDERS
UNION ALL
SELECT 'WEATHER_SEVERITY accepted values',
       SUM(CASE WHEN weather_severity NOT IN ('CLEAR', 'MILD', 'MODERATE', 'SEVERE') THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN weather_severity NOT IN ('CLEAR', 'MILD', 'MODERATE', 'SEVERE') THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_WEATHER_DATA
UNION ALL
SELECT 'UNIT_COST positive',
       SUM(CASE WHEN unit_cost <= 0 THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN unit_cost <= 0 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_PARTS_INVENTORY
UNION ALL
SELECT 'LAT range (-90 to 90)',
       SUM(CASE WHEN lat < -90 OR lat > 90 THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN lat < -90 OR lat > 90 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_FLIGHT_LOGS
UNION ALL
SELECT 'LON range (-180 to 180)',
       SUM(CASE WHEN lon < -180 OR lon > 180 THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN lon < -180 OR lon > 180 THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_FLIGHT_LOGS;


-- ============================================================================
-- SECTION 6: GOLD LAYER ROW COUNT VALIDATION (Silver → Gold)
-- Ensures Gold aggregations have expected row counts
-- ============================================================================

SELECT 'FCT_DELIVERIES vs SILVER_ORDERS' AS check_name,
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.FCT_DELIVERIES) AS gold_count,
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_ORDERS) AS silver_count,
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.FCT_DELIVERIES) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_ORDERS)
            THEN 'PASS' ELSE 'WARN - INVESTIGATE' END AS status
UNION ALL
SELECT 'FCT_MAINTENANCE vs SILVER_MAINTENANCE_LOGS',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.FCT_MAINTENANCE),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_MAINTENANCE_LOGS),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.FCT_MAINTENANCE) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_MAINTENANCE_LOGS)
            THEN 'PASS' ELSE 'WARN - INVESTIGATE' END
UNION ALL
SELECT 'DIM_AIRCRAFT vs SILVER_AIRCRAFT',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.DIM_AIRCRAFT),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_AIRCRAFT),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.DIM_AIRCRAFT) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_AIRCRAFT)
            THEN 'PASS' ELSE 'WARN - INVESTIGATE' END
UNION ALL
SELECT 'DIM_CUSTOMERS vs SILVER_CUSTOMERS',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.DIM_CUSTOMERS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_CUSTOMERS),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.DIM_CUSTOMERS) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_CUSTOMERS)
            THEN 'PASS' ELSE 'WARN - INVESTIGATE' END
UNION ALL
SELECT 'DIM_DEPOTS vs SILVER_DEPOTS',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.DIM_DEPOTS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_DEPOTS),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.DIM_DEPOTS) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_DEPOTS)
            THEN 'PASS' ELSE 'WARN - INVESTIGATE' END
UNION ALL
SELECT 'DIM_DELIVERY_ZONES vs SILVER_DELIVERY_ZONES',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.DIM_DELIVERY_ZONES),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_DELIVERY_ZONES),
       CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.DIM_DELIVERY_ZONES) =
                 (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_DELIVERY_ZONES)
            THEN 'PASS' ELSE 'WARN - INVESTIGATE' END;


-- ============================================================================
-- SECTION 7: GOLD LAYER PRIMARY KEY UNIQUENESS
-- ============================================================================

SELECT 'FCT_DELIVERIES' AS model, 'order_id' AS pk_column,
       COUNT(*) AS total_rows, COUNT(DISTINCT order_id) AS distinct_keys,
       CASE WHEN COUNT(*) = COUNT(DISTINCT order_id) THEN 'PASS' ELSE 'FAIL' END AS status
FROM DRONE_DELIVERY_DB.GOLD.FCT_DELIVERIES
UNION ALL
SELECT 'FCT_MAINTENANCE', 'log_id',
       COUNT(*), COUNT(DISTINCT log_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT log_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.GOLD.FCT_MAINTENANCE
UNION ALL
SELECT 'DIM_AIRCRAFT', 'aircraft_id',
       COUNT(*), COUNT(DISTINCT aircraft_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT aircraft_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.GOLD.DIM_AIRCRAFT
UNION ALL
SELECT 'DIM_CUSTOMERS', 'customer_id',
       COUNT(*), COUNT(DISTINCT customer_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT customer_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.GOLD.DIM_CUSTOMERS
UNION ALL
SELECT 'DIM_DEPOTS', 'depot_id',
       COUNT(*), COUNT(DISTINCT depot_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT depot_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.GOLD.DIM_DEPOTS
UNION ALL
SELECT 'DIM_DELIVERY_ZONES', 'zone_id',
       COUNT(*), COUNT(DISTINCT zone_id),
       CASE WHEN COUNT(*) = COUNT(DISTINCT zone_id) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.GOLD.DIM_DELIVERY_ZONES
UNION ALL
SELECT 'KPI_DELIVERY_PERFORMANCE', 'report_date',
       COUNT(*), COUNT(DISTINCT report_date),
       CASE WHEN COUNT(*) = COUNT(DISTINCT report_date) THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.GOLD.KPI_DELIVERY_PERFORMANCE;


-- ============================================================================
-- SECTION 8: GOLD LAYER NULL CHECK ON CRITICAL COLUMNS
-- ============================================================================

SELECT 'FCT_DELIVERIES.order_id' AS check_column,
       SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END) AS null_count,
       CASE WHEN SUM(CASE WHEN order_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END AS status
FROM DRONE_DELIVERY_DB.GOLD.FCT_DELIVERIES
UNION ALL
SELECT 'FCT_DELIVERIES.customer_id',
       SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.GOLD.FCT_DELIVERIES
UNION ALL
SELECT 'FCT_MAINTENANCE.log_id',
       SUM(CASE WHEN log_id IS NULL THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN log_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.GOLD.FCT_MAINTENANCE
UNION ALL
SELECT 'DIM_AIRCRAFT.aircraft_id',
       SUM(CASE WHEN aircraft_id IS NULL THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN aircraft_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.GOLD.DIM_AIRCRAFT
UNION ALL
SELECT 'DIM_CUSTOMERS.customer_id',
       SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.GOLD.DIM_CUSTOMERS
UNION ALL
SELECT 'KPI_DELIVERY_PERFORMANCE.report_date',
       SUM(CASE WHEN report_date IS NULL THEN 1 ELSE 0 END),
       CASE WHEN SUM(CASE WHEN report_date IS NULL THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.GOLD.KPI_DELIVERY_PERFORMANCE;


-- ============================================================================
-- SECTION 9: CROSS-LAYER CONSISTENCY CHECK
-- Validates data flows correctly through Bronze → Silver → Gold
-- ============================================================================

SELECT 'Total Orders Pipeline' AS check_name,
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DELIVERY.ORDERS) AS source_count,
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_ORDERS) AS bronze_count,
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_ORDERS) AS silver_count,
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.FCT_DELIVERIES) AS gold_count
UNION ALL
SELECT 'Total Aircraft Pipeline',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DEPOT.AIRCRAFT),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_AIRCRAFT),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_AIRCRAFT),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.DIM_AIRCRAFT)
UNION ALL
SELECT 'Total Customers Pipeline',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.DELIVERY.CUSTOMERS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_CUSTOMERS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_CUSTOMERS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.DIM_CUSTOMERS)
UNION ALL
SELECT 'Total Maintenance Pipeline',
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.RECORDS.MAINTENANCE_LOGS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.BRONZE.BRONZE_MAINTENANCE_LOGS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.SILVER.SILVER_MAINTENANCE_LOGS),
       (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.GOLD.FCT_MAINTENANCE);


-- ============================================================================
-- SECTION 10: CORTEX AI SENTIMENT VALIDATION
-- Validates AI-enriched columns in Silver layer
-- ============================================================================

SELECT 'Sentiment populated' AS check_name,
       COUNT(*) AS total_records,
       SUM(CASE WHEN sentiment_score IS NOT NULL THEN 1 ELSE 0 END) AS with_sentiment,
       ROUND(SUM(CASE WHEN sentiment_score IS NOT NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) AS pct_populated,
       CASE WHEN SUM(CASE WHEN sentiment_score IS NOT NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*) >= 95 THEN 'PASS' ELSE 'FAIL' END AS status
FROM DRONE_DELIVERY_DB.SILVER.SILVER_DELIVERY_FEEDBACK
UNION ALL
SELECT 'Sentiment label valid',
       COUNT(*),
       SUM(CASE WHEN sentiment_label IN ('POSITIVE', 'NEGATIVE', 'NEUTRAL') THEN 1 ELSE 0 END),
       ROUND(SUM(CASE WHEN sentiment_label IN ('POSITIVE', 'NEGATIVE', 'NEUTRAL') THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1),
       CASE WHEN SUM(CASE WHEN sentiment_label NOT IN ('POSITIVE', 'NEGATIVE', 'NEUTRAL') THEN 1 ELSE 0 END) = 0 THEN 'PASS' ELSE 'FAIL' END
FROM DRONE_DELIVERY_DB.SILVER.SILVER_DELIVERY_FEEDBACK;


-- ============================================================================
-- SECTION 11: SUMMARY DASHBOARD QUERY
-- Run last - provides overall validation health check
-- ============================================================================

SELECT
    'BRONZE LAYER' AS layer,
    18 AS expected_tables,
    (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'BRONZE') AS actual_tables,
    CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'BRONZE') = 18 THEN 'PASS' ELSE 'FAIL' END AS status
UNION ALL
SELECT
    'SILVER LAYER',
    17,
    (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA = 'SILVER'),
    CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA = 'SILVER') = 17 THEN 'PASS' ELSE 'FAIL' END
UNION ALL
SELECT
    'GOLD LAYER',
    7,
    (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'GOLD'),
    CASE WHEN (SELECT COUNT(*) FROM DRONE_DELIVERY_DB.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'GOLD') = 7 THEN 'PASS' ELSE 'FAIL' END;
